name: setup
inputs:
  build:
    description: build
    required: false
    default: true
  playwright:
    description: install playwright
    required: false
    default: true
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 22

    - run: corepack enable
      shell: bash

    - run: pnpm i
      shell: bash

    - run: pnpm build
      shell: bash
      if: ${{ inputs.build == 'true' }}

    - run: npx playwright install chromium
      shell: bash
      if: ${{ inputs.playwright == 'true' }}
