name: trigger-nightly
on:
  # schedule:
  #   - cron: '0 0 * * *'
  # workflow_dispatch:
  push:

permissions:
  contents: write
  # pull-requests: write
  # repository-projects: write

jobs:
  trigger-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr checkout canary
        env:
          GITHUB_TOKEN: ${{ secrets.REACT_NIGHTLY_TRIGGER_TOKEN }}
      - name: push commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          NIGHTLY_VERSION=$(npm view react dist-tags.canary --json | jq -r 'split("-") | .[-2:] | join("-")')
          git commit --allow-empty -m "chore: nightly ${NIGHTLY_VERSION}"
          git push https://x-access-token:${{ secrets.REACT_NIGHTLY_TRIGGER_TOKEN }}@github.com/${{ github.repository }}.git
