name: trigger-nightly
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  update-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh pr checkout canary
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          NIGHTLY_VERSION=$(npm view react dist-tags.canary --json | jq -r 'split("-") | .[-2:] | join("-")')
          git commit --allow-empty -m "chore: nightly ${NIGHTLY_VERSION}"
          git push
