name: trigger-nightly
on:
  # schedule:
  #   - cron: '0 0 * * *'
  # workflow_dispatch:
  push:

# permissions:
#   contents: write
#   pull-requests: write
#   repository-projects: write

jobs:
  trigger-nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: canary
          token: ${{ secrets.REACT_NIGHTLY_TRIGGER_TOKEN }}
      - name: push commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          NIGHTLY_VERSION=$(npm view react dist-tags.canary --json | jq -r 'split("-") | .[-2:] | join("-")')
          git commit --allow-empty -m "chore: nightly ${NIGHTLY_VERSION}"
          git push

  trigger-nightly-plugin-rsc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hi-ogawa/vite-plugin-react
          ref: chore-rsc-nightly
          token: ${{ secrets.REACT_NIGHTLY_TRIGGER_TOKEN }}
      - name: push commit
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          NIGHTLY_VERSION=$(npm view react dist-tags.canary --json | jq -r 'split("-") | .[-2:] | join("-")')
          git commit --allow-empty -m "chore: nightly ${NIGHTLY_VERSION}"
          git push
